
name: Build and deploy container app to Azure Web App - nodejsexpresserver

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Build
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: nodejsconatiner.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername}}
        password: ${{ secrets.AzureAppService_ContainerPassword}}
    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: nodejsconatiner.azurecr.io/${{ secrets.AzureAppService_ContainerUsername }}/nodejsimgapp:${{ github.sha }}
        file: ./Dockerfile

    
